// Generated by CoffeeScript 1.7.1
var client, clientGenerator, message, ttypes, user, user1;

clientGenerator = require("./NodejsClientGenerator/ClientGenerator");

client = clientGenerator.client("MessageService");

ttypes = clientGenerator.ttypes("MessageService");

user = new ttypes.UserId({
  uid: "123",
  type: "csr",
  clientType: "mobile"
});

user1 = new ttypes.UserId({
  uid: "123",
  type: "csr",
  clientType: "mobile"
});

message = new ttypes.Message({
  type: 123,
  datetime: new Date().toString(),
  createdAt: Date.now(),
  content: "superwolf",
  fromId: "superowlf"
});

setInterval(function() {
  return client.online(user, function(err) {
    return client.sendMessageToUserIdCollection([user, user1], "message", message, function(err) {
      return client.offline(user, function(err) {
        return client.sendMessage(user, "message", message, function(err) {});
      });
    });
  });
}, 1000);
