// Generated by CoffeeScript 1.7.1
module.exports = {
  development: {
    domain: "localhost",
    port: 10000,
    max: 10,
    min: 0,
    idleTimeoutMillis: 30000,
    log: true,
    transport: "TBufferedTransport"
  },
  test: {
    domain: "127.0.0.1",
    port: 10000,
    max: 10,
    min: 2,
    idleTimeoutMillis: 30000,
    log: false,
    transport: "TBufferedTransport"
  },
  integration: {
    domain: "192.168.26.90",
    port: 10000,
    max: 10,
    min: 2,
    idleTimeoutMillis: 30000,
    log: false,
    transport: "TBufferedTransport"
  },
  production: {
    domain: "Chat-YG-112.ytx.com",
    port: 10000,
    max: 100,
    min: 20,
    idleTimeoutMillis: 30000,
    log: true,
    transport: "TBufferedTransport"
  }
};
