// Generated by CoffeeScript 1.7.1
var buildPoolMethod, exportClient;

buildPoolMethod = function(serviceName, service, config) {
  var crmClientPool, filterMethod, poolClient;
  poolClient = {};
  crmClientPool = require('./PoolGenerator').createCRMClientPool(serviceName, service, config);
  filterMethod = function() {
    var prop, _i, _len, _ref, _results;
    _ref = Object.keys(service.Client.prototype);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      prop = _ref[_i];
      if (prop.indexOf('send_') === -1 && prop.indexOf('recv_') === -1) {
        _results.push(prop);
      }
    }
    return _results;
  };
  filterMethod().map(function(method) {
    return poolClient[method] = function() {
      var _args;
      _args = Array.prototype.slice.call(arguments);
      return crmClientPool.acquire(function(err, client) {
        var callback, _callback;
        if (typeof _args[_args.length - 1] === 'function') {
          _callback = _args[_args.length - 1];
        } else {
          _callback = function() {};
          _args.push(_callback);
        }
        if (err) {
          console.error("" + __filename + ".acquire " + method + " ", err);
          _callback(err);
          return;
        }
        callback = function() {
          crmClientPool.release(client);
          return _callback.apply(null, arguments);
        };
        _args[_args.length - 1] = callback;
        return client[method].apply(client, _args);
      });
    };
  });
  return poolClient;
};

exportClient = {};

module.exports = {
  client: function(serviceName) {
    var config, service;
    service = require("../ServiceCollection/" + serviceName + "Protocol/gen-nodejs/" + serviceName);
    config = require("../ServiceCollection/" + serviceName + "Protocol/config");
    if (!exportClient[serviceName]) {
      exportClient[serviceName] = buildPoolMethod(serviceName, service, config);
    }
    return exportClient[serviceName];
  },
  ttypes: function(serviceName) {
    return require("../ServiceCollection/" + serviceName + "Protocol/gen-nodejs/" + serviceName + "_types");
  },
  contract: function(serviceName) {
    return require("../ServiceCollection/" + serviceName + "Protocol/gen-nodejs/" + serviceName);
  }
};
